In [1]:
import pandas as pd

In [2]:
# Only one with methodology
df1 = pd.read_csv('DBassign1/2016-GHG_Emissions.csv')

In [3]:
# Columns in Methodologies table
m_id = 'methodology_id'
m = 'primary_methodology'
m_det = 'details'
m_eid = 'emission_id'

# placeholders to find correct m_eid
org_no = 'org_no'

In [5]:
df1.rename(columns={'Primary Methodology': m, 'Methodology Details': m_det, 'Account Number': org_no}, inplace=True)

In [6]:
tmp_m_df = df1[[m, m_det,org_no]]
tmp_m_df

,primary_methodology,details,org_no
0,2006 IPCC Guidelines for National Greenhouse G...,2006 IPCC Guidelines for National Greenhouse G...,35894
1,Global Protocol for Community-Scale Greenhouse...,A GPC Compliant dataset has been established f...,35898
2,Global Protocol for Community-Scale Greenhouse...,Also utilized the U.S. Community Protocol for ...,54128
3,U.S. Community Protocol for Accounting and Rep...,A note regarding how double counting is avoide...,35879
4,International Emissions Analysis Protocol (ICLEI),as adapted by ICLEI Canada for use in the FCM'...,50558
...,...,...,...
182,Global Protocol for Community-Scale Greenhouse...,NaN,59165
183,U.S. Community Protocol for Accounting and Rep...,NaN,31108
184,Global Protocol for Community-Scale Greenhouse...,NaN,31167
185,International Emissions Analysis Protocol (ICLEI),NaN,54088
186,Global Protocol for Community-Scale Greenhouse...,NaN,42178

In [7]:
tmp_m_df.reset_index(drop=True, inplace=True)
tmp_m_df[m_id] = tmp_m_df.index + 1
tmp_m_df

C:\Users\Caroline\AppData\Local\Temp\ipykernel_10604\3192193903.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tmp_m_df[m_id] = tmp_m_df.index + 1

,primary_methodology,details,org_no,methodology_id
0,2006 IPCC Guidelines for National Greenhouse G...,2006 IPCC Guidelines for National Greenhouse G...,35894,1
1,Global Protocol for Community-Scale Greenhouse...,A GPC Compliant dataset has been established f...,35898,2
2,Global Protocol for Community-Scale Greenhouse...,Also utilized the U.S. Community Protocol for ...,54128,3
3,U.S. Community Protocol for Accounting and Rep...,A note regarding how double counting is avoide...,35879,4
4,International Emissions Analysis Protocol (ICLEI),as adapted by ICLEI Canada for use in the FCM'...,50558,5
...,...,...,...,...
182,Global Protocol for Community-Scale Greenhouse...,NaN,59165,183
183,U.S. Community Protocol for Accounting and Rep...,NaN,31108,184
184,Global Protocol for Community-Scale Greenhouse...,NaN,31167,185
185,International Emissions Analysis Protocol (ICLEI),NaN,54088,186
186,Global Protocol for Community-Scale Greenhouse...,NaN,42178,187

In [8]:
e_df = pd.read_csv('DBassign1/emission_table.csv', sep=';')
e_df

     emission_id  Organization_id                       gases_included
0              1            35894                        CO2; CH4; N2O
1              2            35898  CO2; PFCs; CH4; SF6; N2O; NF3; HFCs
2              3            54128                        CO2; CH4; N2O
3              4            35879                        CO2; CH4; N2O
4              5            50558                        CO2; CH4; N2O
..           ...              ...                                  ...
864          865            58424                                  NaN
865          866            60229                                  NaN
866          867            60577                                  NaN
867          868            60588                                  NaN
868          869            63543                                  NaN

[869 rows x 3 columns]

In [10]:
emission_mapping = e_df[['Organization_id', 'emission_id']].set_index('Organization_id')['emission_id']

tmp_m_df[m_eid] = tmp_m_df[org_no].map(emission_mapping)

tmp_m_df.drop(columns=[org_no], inplace=True)

tmp_m_df

C:\Users\Caroline\AppData\Local\Temp\ipykernel_10604\2264499173.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tmp_m_df[m_eid] = tmp_m_df[org_no].map(emission_mapping)
C:\Users\Caroline\AppData\Local\Temp\ipykernel_10604\2264499173.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tmp_m_df.drop(columns=[org_no], inplace=True)

,primary_methodology,details,methodology_id,emission_id
0,2006 IPCC Guidelines for National Greenhouse G...,2006 IPCC Guidelines for National Greenhouse G...,1,1
1,Global Protocol for Community-Scale Greenhouse...,A GPC Compliant dataset has been established f...,2,2
2,Global Protocol for Community-Scale Greenhouse...,Also utilized the U.S. Community Protocol for ...,3,3
3,U.S. Community Protocol for Accounting and Rep...,A note regarding how double counting is avoide...,4,4
4,International Emissions Analysis Protocol (ICLEI),as adapted by ICLEI Canada for use in the FCM'...,5,5
...,...,...,...,...
182,Global Protocol for Community-Scale Greenhouse...,NaN,183,176
183,U.S. Community Protocol for Accounting and Rep...,NaN,184,177
184,Global Protocol for Community-Scale Greenhouse...,NaN,185,178
185,International Emissions Analysis Protocol (ICLEI),NaN,186,179
186,Global Protocol for Community-Scale Greenhouse...,NaN,187,180

In [11]:
tmp_m_df.to_csv('DBassign1/Table files/csv/methodologies_table.csv')

In [12]:
import util
util.write_sql_insert_file('DBassign1/Table files/sql/methodologies_table.sql', tmp_m_df, 'Methodologies')